---
output:
  html_document: default
  pdf_document: default
---
Summary of data fields in tidyData.txt.

## Identifiers:

* subject - id of the test subject
* activity - activity performed when the corresponding measurements were taken

Activity Labels:

* WALKING
* WALKING_UPSTAIRS
* WALKING_DOWNSTAIRS
* SITTING
* STANDING
* LAYING


## Measurements:

* tBodyAcc-mean-X 
* tBodyAcc-mean-Y 
* tBodyAcc-mean-Z 
* tBodyAcc-std-X 
* tBodyAcc-std-Y 
* tBodyAcc-std-Z 
* tGravityAcc-mean-X 
* tGravityAcc-mean-Y 
* tGravityAcc-mean-Z 
* tGravityAcc-std-X 
* tGravityAcc-std-Y 
* tGravityAcc-std-Z 
* tBodyAccJerk-mean-X 
* tBodyAccJerk-mean-Y 
* tBodyAccJerk-mean-Z 
* tBodyAccJerk-std-X 
* tBodyAccJerk-std-Y 
* tBodyAccJerk-std-Z 
* tBodyGyro-mean-X 
* tBodyGyro-mean-Y 
* tBodyGyro-mean-Z 
* tBodyGyro-std-X 
* tBodyGyro-std-Y 
* tBodyGyro-std-Z 
* tBodyGyroJerk-mean-X 
* tBodyGyroJerk-mean-Y 
* tBodyGyroJerk-mean-Z 
* tBodyGyroJerk-std-X 
* tBodyGyroJerk-std-Y 
* tBodyGyroJerk-std-Z 
* tBodyAccMag-mean 
* tBodyAccMag-std 
* tGravityAccMag-mean 
* tGravityAccMag-std 
* tBodyAccJerkMag-mean 
* tBodyAccJerkMag-std 
* tBodyGyroMag-mean 
* tBodyGyroMag-std 
* tBodyGyroJerkMag-mean 
* tBodyGyroJerkMag-std 
* fBodyAcc-mean-X 
* fBodyAcc-mean-Y 
* fBodyAcc-mean-Z 
* fBodyAcc-std-X 
* fBodyAcc-std-Y 
* fBodyAcc-std-Z 
* fBodyAcc-meanFreq-X 
* fBodyAcc-meanFreq-Y 
* fBodyAcc-meanFreq-Z 
* fBodyAccJerk-mean-X 
* fBodyAccJerk-mean-Y 
* fBodyAccJerk-mean-Z 
* fBodyAccJerk-std-X 
* fBodyAccJerk-std-Y 
* fBodyAccJerk-std-Z 
* fBodyAccJerk-meanFreq-X 
* fBodyAccJerk-meanFreq-Y 
* fBodyAccJerk-meanFreq-Z 
* fBodyGyro-mean-X 
* fBodyGyro-mean-Y 
* fBodyGyro-mean-Z 
* fBodyGyro-std-X 
* fBodyGyro-std-Y 
* fBodyGyro-std-Z 
* fBodyGyro-meanFreq-X 
* fBodyGyro-meanFreq-Y 
* fBodyGyro-meanFreq-Z 
* fBodyAccMag-mean 
* fBodyAccMag-std 
* fBodyAccMag-meanFreq 
* fBodyBodyAccJerkMag-mean 
* fBodyBodyAccJerkMag-std 
* fBodyBodyAccJerkMag-meanFreq 
* fBodyBodyGyroMag-mean 
* fBodyBodyGyroMag-std 
* fBodyBodyGyroMag-meanFreq 
* fBodyBodyGyroJerkMag-mean 
* fBodyBodyGyroJerkMag-std 
* fBodyBodyGyroJerkMag-meanFreq 
* angletBodyAccMean,gravity 
* angletBodyAccJerkMean,gravityMean 
* angletBodyGyroMean,gravityMean 
* angletBodyGyroJerkMean,gravityMean 
* angleX,gravityMean 
* angleY,gravityMean 
* angleZ,gravityMean


## Data Transformation from the original set

* training and test data were combined into one 
* subject, activity, and measurements were combined
* only measurements that reflected mean or std were kept, the rest were discarded
* activity id was replaced with activity label
* tidy set of the mean value of each variable for each subject and activity pair was created
